goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../kanban/state.js", ['kanban.state'], ['cljs.core']);
goog.addDependency("../om/next/cache.js", ['om.next.cache'], ['cljs.core']);
goog.addDependency("../clojure/zip.js", ['clojure.zip'], ['cljs.core']);
goog.addDependency("../om/next/impl/parser.js", ['om.next.impl.parser'], ['cljs.core']);
goog.addDependency("../om/next/protocols.js", ['om.next.protocols'], ['cljs.core']);
goog.addDependency("../clojure/walk.js", ['clojure.walk'], ['cljs.core']);
goog.addDependency("../om/next.js", ['om.next'], ['om.next.cache', 'clojure.zip', 'om.next.impl.parser', 'goog.string', 'goog.debug.Console', 'cljs.core', 'goog.object', 'goog.log', 'om.next.protocols', 'clojure.walk']);
goog.addDependency("../kanban/reconciler.js", ['kanban.reconciler'], ['cljs.core', 'goog.object', 'kanban.state', 'om.next']);
goog.addDependency("../react.inc.js", ['cljsjs.react'], []);
goog.addDependency("../react-dom.inc.js", ['cljsjs.react.dom'], ['cljsjs.react']);
goog.addDependency("../om/dom.js", ['om.dom'], ['cljs.core', 'goog.object', 'cljsjs.react', 'cljsjs.react.dom']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../kanban/util.js", ['kanban.util'], ['cljs.core', 'clojure.string']);
goog.addDependency("../kanban/components/card.js", ['kanban.components.card'], ['goog.string', 'cljs.core', 'om.dom', 'goog.object', 'goog.string.format', 'kanban.util', 'om.next']);
goog.addDependency("../kanban/components/card_editor.js", ['kanban.components.card_editor'], ['kanban.components.card', 'cljs.core', 'om.dom', 'goog.object', 'om.next']);
goog.addDependency("../kanban/components/boards_menu.js", ['kanban.components.boards_menu'], ['cljs.core', 'om.dom', 'goog.object', 'om.next']);
goog.addDependency("../kanban/components/about.js", ['kanban.components.about'], ['cljs.core', 'om.dom']);
goog.addDependency("../kanban/parsing/users.js", ['kanban.parsing.users'], ['cljs.core', 'kanban.reconciler']);
goog.addDependency("../kanban/parsing/cards.js", ['kanban.parsing.cards'], ['kanban.parsing.users', 'cljs.core', 'kanban.reconciler']);
goog.addDependency("../kanban/parsing/lanes.js", ['kanban.parsing.lanes'], ['kanban.parsing.cards', 'cljs.core', 'kanban.reconciler']);
goog.addDependency("../kanban/parsing/boards.js", ['kanban.parsing.boards'], ['cljs.core', 'kanban.reconciler', 'kanban.parsing.lanes']);
goog.addDependency("../kanban/components/lane.js", ['kanban.components.lane'], ['kanban.components.card', 'cljs.core', 'om.dom', 'goog.object', 'om.next']);
goog.addDependency("../kanban/components/board.js", ['kanban.components.board'], ['cljs.core', 'om.dom', 'goog.object', 'kanban.components.lane', 'om.next']);
goog.addDependency("../kanban/app.js", ['kanban.app'], ['kanban.components.card', 'kanban.components.card_editor', 'cljs.core', 'om.dom', 'kanban.components.boards_menu', 'kanban.components.about', 'kanban.parsing.boards', 'kanban.components.board', 'kanban.reconciler', 'kanban.components.lane', 'om.next']);
goog.addDependency("../clojure/browser/event.js", ['clojure.browser.event'], ['cljs.core', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events']);
goog.addDependency("../clojure/browser/net.js", ['clojure.browser.net'], ['goog.net.xpc.CfgFields', 'goog.net.XhrIo', 'goog.json', 'goog.Uri', 'cljs.core', 'goog.net.EventType', 'goog.net.xpc.CrossPageChannel', 'goog.net.WebSocket', 'clojure.browser.event']);
goog.addDependency("../adzerk/boot_reload/connection.js", ['adzerk.boot_reload.connection'], ['cljs.core', 'clojure.browser.net']);
goog.addDependency("../adzerk/boot_reload/reload.js", ['adzerk.boot_reload.reload'], ['goog.net.jsloader', 'goog.Uri', 'cljs.core', 'goog.async.DeferredList', 'clojure.string']);
goog.addDependency("../adzerk/boot_reload/display.js", ['adzerk.boot_reload.display'], ['adzerk.boot_reload.connection', 'goog.dom', 'goog.Timer', 'cljs.core', 'goog.events.EventType', 'clojure.string', 'goog.events']);
goog.addDependency("../adzerk/boot_reload/websocket.js", ['adzerk.boot_reload.websocket'], ['cljs.core', 'clojure.browser.net', 'goog.net.WebSocket', 'clojure.browser.event']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../adzerk/boot_reload/client.js", ['adzerk.boot_reload.client'], ['adzerk.boot_reload.connection', 'adzerk.boot_reload.reload', 'adzerk.boot_reload.display', 'goog.net.jsloader', 'cljs.core', 'adzerk.boot_reload.websocket', 'clojure.browser.net', 'cljs.reader', 'clojure.browser.event']);
goog.addDependency("../adzerk/boot_reload.js", ['adzerk.boot_reload'], ['cljs.core', 'adzerk.boot_reload.client', 'kanban.app']);
goog.addDependency("../boot/cljs/main707.js", ['boot.cljs.main707'], ['adzerk.boot_reload', 'cljs.core', 'kanban.app']);
